public enum TokenType {
    IDENTIFIANT, NOMBRE, MOT_CLE, CHAINE, COMMENTAIRE,
    WHILE, ELSE, IF, FOR, DEF, PASS, TRUE, FALSE, NONE,
    CHAHINEZ,  
    DEUX_POINTS, EGAL, PLUS, MOINS, FOIS, DIVISE,
    INDENT, DEDENT, NOUVELLE_LIGNE, FIN_FICHIER
}
    
